// CONSTANTS
export const appConstants = {
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  ADD_TODO_FAILURE: "ADD_TODO_FAILURE",

  REMOVE_TODO_ITEM: "REMOVE_TODO_ITEM",

  TOGGLE_TODO_STATUS: "TOGGLE_TODO_STATUS",

  GET_TODO_REQUEST: "GET_TODO_REQUEST",
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  GET_TODO_FAILURE: "GET_TODO_FAILURE"
};
